[tool.poetry]
name = "django-types"
version = "0.5.2"
description = "Type stubs for Django"
repository = "https://github.com/sbdchd/django-types"
readme = "README.md"
authors = ["Steve Dignam <steve@dignam.xyz>"]
license = "MIT"
keywords = ["django", "types", "mypy", "stubs"]

packages = [
  { include = "django-stubs" },
  { include = "psycopg2-stubs" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "20.8b1",allows-prereleases = true}
pytest = "^6.1"
wheel = "^0.35.1"
mypy = "^0.790.0"
isort = "^5.6"
django = "^3.1"
flake8 = "^3.8"
psycopg2 = "^2.8"

[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile="black"

[build-system]
requires = ["poetry>=0.12", "setuptools"]
build-backend = "poetry.masonry.api"
