[tool.poetry]
name = "django-types"
version = "0.9.0"
description = "Type stubs for Django"
repository = "https://github.com/sbdchd/django-types"
readme = "README.md"
authors = ["Steve Dignam <steve@dignam.xyz>"]
license = "MIT"
keywords = ["django", "types", "mypy", "stubs"]

packages = [
  { include = "django-stubs" },
  { include = "psycopg2-stubs" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "20.8b1"
pytest = "6.2.2"
wheel = "0.35.1"
mypy = "0.790"
isort = "5.7.0"
Django = "3.1.7"
flake8 = "3.8.4"
psycopg2 = "2.8.6"

[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile="black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
