# Taken from: https://jacobian.org/til/github-actions-poetry/
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Install python dependencies
        run: poetry install --no-interaction

      - name: Install node dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: lint
        run: ./s/lint
